pose:
  0
joints:
  open:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.07
    - 0.0
    - 0.0
    - 0.3

  close:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - -0.7
    
  home:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  active_home:
    - 0.0
    - 1.535
    - -1.4989
    - 2.7457
    - 2.2593
    - -0.315
    - 0.44
    - 0.2

  pre_active_home:
    - 0.0
    - 1.2108
    - -1.6000
    - 3.187
    - 2.046
    - 0.0192
    - 0.0411

  pre_pickup_cube:
    - 0.0
    - 0.25
    - 0.0
    - 0.99
    - 0
    - 1.85
    - 0

  pickup_cube:
    - -0.019
    - 0.183
    - 0.0
    - 1.67
    - 0.0
    - 1.28
    - 0.014

  pre_pickup_ball:
    - 0.0
    - -0.415
    - 0.0
    - -0.762
    - 0.0
    - -1.747
    - 0

  # Handoff 1
  pre_handoff_1: #done
    - 0.32
    - 1.06 
    - -1.43  
    - 2.73 
    - 2.0 
    - -0.13
    - -0.71
    - 0.2 

  handoff_1a: #done
    - -0.12
    - 1.19
    - -1.14
    - 2.80
    - 2.0
    - -0.30
    - -0.86
    - 0.2        # move to handoff position

  handoff_1b: # done
    - -0.12
    - 1.19
    - -1.14
    - 2.80
    - 2.0
    - -0.30
    - -0.86
    - 1      # open gripper

  handoff_1c: # done
    - 0.32
    - 1.06 
    - -1.43  
    - 2.73 
    - 2.0 
    - -0.13
    - -0.71
    - 0.2       # move back to active home


  # Handoff 2
  pre_handoff_2: # done
    - 0.32
    - 1.06 
    - -1.43  
    - 2.73 
    - 2.0 
    - -0.13
    - -0.71
    - 1 

  handoff_2a: # done
    - -0.12
    - 1.2
    - -1.39
    - 2.78
    - 2.0
    - -0.38
    - -1.65
    - 1           # move toward the handoff position

  handoff_2b:
    - -0.12
    - 1.2
    - -1.39
    - 2.78
    - 2.0
    - -0.38
    - -1.65
    - 0.1           # handoff position with gripper open

  handoff_2c:
    - -0.06
    - 1.440
    - -1.238
    - 2.7368
    - 2.0017
    - -0.2400
    - 1.6178
    - 0           # handoff position with gripper closed

  handoff_2d:
    - -0.22
    - 1.535
    - -1.4989
    - 2.7457
    - 2.2593
    - -0.315
    - 0.44
    - 0          # back home


  discard_0:
    - -0.1043
    - 1.5178
    - -1.286
    - 2.2866
    - 2.385
    - -1.115
    - 0.4152
    - 1

  # Handoff 3
  pre_handoff_3:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_3a:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_3b:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_3c:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  handoff_3d:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  
  # Must be labeled step_x.
  # These are looped through autonomously to fold and unfold
  # Any number of steps can be used
  # Must start at step_0

  # folding and unfolding
  # done
  folding:
    step_0:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    step_1:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - -2.81

    step_2:
      - 0.126
      - 0.0
      - 0.0
      - -0.024
      - -0.03
      - -2.81

    step_3:
      - 0.29
      - 0.02
      - -0.18
      - -0.05
      - -0.01
      - -2.81

    step_4:
      - 0.43
      - 0.02
      - -0.32
      - -0.05
      - 0.0
      - -2.81

    step_5:
      - 0.6
      - 0.03
      - -0.64
      - -0.045
      - 0.54
      - 0.0

    step_6:
      - 0.84
      - 0.04
      - -0.89
      - -0.01
      - 0.56
      - 0.0

    step_7:
      - 1.17
      - 0.05
      - -1.1
      - -0.1
      - 0.6
      - 0.0

    step_8:
      - 1.53
      - 0.06
      - -1.11
      - -0.09
      - 0.228
      - 0.0

    step_9:
      - 1.52
      - -0.04
      - -0.91
      - 0.0
      - 0.227
      - 0.0

    step_10:
      - 1.52
      - -0.13
      - -0.658
      - 0.135
      - -0.3
      - 0.0

    step_11:
      - 1.51
      - -0.17
      - -0.356
      - 0.079
      - -0.3
      - 0.0

    step_12:
      - 1.55
      - -0.43
      - -0.44
      - 0.6
      - -0.293
      - 0.0

    step_13:
      - 1.556
      - -0.537
      - -0.254
      - 0.418
      - -0.286
      - 0.0

    step_14:
      - 1.513
      - -0.06
      - -0.287
      - 3.04
      - -0.279
      - 0.0

    step_15:
      - 1.29
      - 0.0
      - 1.92
      - 3.46
      - -0.131
      - 0.0

    step_16:
      - 1.29
      - 0.0
      - 1.92
      - 3.46
      - -0.131
      - -2.81

    step_17:
      - 1.29
      - 0.0
      - 1.92
      - 3.46
      - -0.131
      - 0.0

  refolding:
    step_0:
      - 0.12
      - 1.69
      - -1.2
      - 1.66
      - 2.29
      - -1.61
      - 0.0
      - 0.0

    step_1:
      - 0.400
      - 1.61
      - -1.30
      - 0.000
      - 2.15
      - 0.03
      - 0.0
      - 0.0

    step_2:
      - 0.400
      - 1.61
      - -1.30
      - 0.000
      - 0.211
      - 0.03
      - 0.0
      - 0.0

    step_3:
      - 0.400
      - 1.61
      - -1.00
      - 0.000
      - -0.3
      - 0.03
      - 0.0
      - 0.0
    
    step_4:
      - 0.43
      - 1.040
      - -0.883
      - 0.0
      - -0.23
      - 0.0
      - 0.0
      - 0.0

    step_5:
      - 0.04
      - 0.3305
      - -0.55
      - 0.0
      - 0.35
      - 0.0
      - 0.0
      - 0.0

    step_6:
      - 0.04
      - 0.3305
      - -0.55
      - 0.0
      - 0.35
      - 0.0
      - 0.0
      - 0.0

    step_7:
      - -0.13
      - 0.3316
      - -0.16
      - 0.0
      - 0.37
      - -0.32
      - 0.0
      - 0.0

    step_8:
      - 0.4633
      - 0.3316
      - -0.6016
      - 0.0
      - 0.4888
      - -0.1450
      - 0.0
      - 0.0

    step_9:
      - 0.0
      - 0.2443 
      - 0.0 
      - 0.0174
      - 0.0872
      - 0.0
      - 0.0
      - 0.64

    step_10:
      - 0.0
      - 0.0 
      - 0.0 
      - 0.0 
      - 0.0 
      - 0.0 
      - 0.0
      - 0.3

    step_11:
      - 0.0
      - 0.0 
      - 0.0 
      - 0.0 
      - 0.0 
      - 0.0 
      - 0.0
      - 0.0

    

# pickup object 1 poses
# done-ish
  pickup_obj_1:
    step_0: # pretty much active home
      - 0.05
      - 1.55
      - -1.21
      - 2.27
      - 2.27
      - 0.01
      - -0.02
      - 0.0

    step_1: #
      - 0.0
      - 1.58
      - -1.34
      - 2.73
      - 2.25
      - 0.04
      - 0.32
      - 0.4

    step_2: #
      - 0.0
      - 1.27
      - -1.31
      - 2.98
      - 2.02
      - 0.0 
      - 0.32 
      - 0.6

    step_3: # on top of the post
      - 0.0
      - 1.18
      - -1.32
      - 3.2
      - 1.83
      - -0.14
      - 0.16
      - 0.6

    step_4: # boutta grab the ball
      - -0.08
      - 1.22
      - -1.16
      - 3.26
      - 1.94
      - -0.08
      - -0.2
      - 0.6

    step_5: # grabbed the ball
      - -0.08
      - 1.22
      - -1.16
      - 3.26
      - 1.94
      - -0.08
      - -0.2
      - 0.2

    step_6: # halfway up the pole
      - -0.08
      - 1.22
      - -1.31
      - 3.24
      - 2.04
      - -0.17
      - -0.144
      - 0.2

    step_7: # off the pole
      - -0.08
      - 1.22
      - -1.50
      - 3.22
      - 1.98
      - -0.26
      - -0.12
      - 0.2

    step_8: #
      - -0.08
      - 1.22
      - -1.56
      - 3.21
      - 1.95
      - -0.34
      - -0.14
      - 0.1

    step_9: #
      - -0.08
      - 1.22
      - -1.56
      - 3.21
      - 1.95
      - -0.98
      - -0.14
      - 0.1

    step_10: # done
      - 0.05
      - 1.55
      - -1.21
      - 2.27
      - 2.27
      - 0.01
      - -0.02
      - 0.1

# pickup object 2 positions
  pickup_obj_3:
    step_0: # pretty much active home
      - 0.05
      - 1.55
      - -1.21
      - 2.27
      - 2.27
      - 0.01
      - -0.02
      - 0.0

    step_1: #
      - 0.0
      - 1.58
      - -1.34
      - 2.73
      - 2.25
      - 0.04
      - 0.32
      - 0.4

    step_2: #
      - 0.0
      - 1.27
      - -1.31
      - 2.98
      - 2.02
      - 0.0 
      - 0.32 
      - 0.6

    step_3: # on top of the post
      - 0.0
      - 1.18
      - -1.32
      - 3.2
      - 1.83
      - -0.16
      - 0.16
      - 0.6

    step_4: #
      - -0.1
      - 1.2 
      - -0.95
      - 3.2
      - 1.94
      - -0.05
      - -0.24
      - 0.6

    step_5: #
      - -0.12
      - 1.5
      - -1.03
      - 3.16
      - 2.16
      - -0.03
      - -0.3
      - 0.5

    step_6: # grabbed
      - -0.12
      - 1.5
      - -1.03
      - 3.16
      - 2.16
      - -0.03
      - -0.3
      - 0.25

    step_7: # move up and grab some more
      - -0.13
      - 1.51
      - -1.13
      - 3.16
      - 2.15
      - -0.08
      - -0.323
      - 0.2

    step_8: # move up and grab even more
      - -0.13
      - 1.27
      - -1.22
      - 3.15
      - 1.94
      - -0.12
      - -0.33 
      - 0.1

    step_9: # off the pole
      - -0.09
      - 1.3 
      - -1.43
      - 3.14
      - 1.77
      - -0.17
      - -0.33
      - 0.1

    step_10: # move away
      - -0.09
      - 1.3
      - -1.43
      - 3.14
      - 1.93
      - -0.97
      - -0.33
      - 0.1

    step_11: # back to step 0
      - 0.05
      - 1.55
      - -1.21
      - 2.27
      - 2.27
      - 0.01
      - -0.02
      - 0.0

  discard_obj:
    step_0:
      -0.0

  pickup_obj_2:
    step_0:
      -0.0

grip_pose:
  open: 2
  close: 0
  half_close: 0.5
  grasp_cube: 0.16