arm2d2/controllers:
  state:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  velocity:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    gains:
      joint_1: {p: 10,  d: 0, i: 0.1, i_clamp: 0.5}
      joint_2: {p: 10,  d: 0, i: 0, i_clamp: 1}
      joint_3: {p: 10,  d: 0.01, i: 0, i_clamp: 1}
      joint_4: {p: 10,  d: 0, i: 0, i_clamp: 1}
      joint_5: {p: 1,  d: 0, i: 0, i_clamp: 1}
      joint_6: {p: 6, d: 0.7, i: 0, i_clamp: 1}
      joint_7: {p: 7, d: 0.9, i: 0, i_clamp: 1}
    constraints:
      goal_time: 100
      stopped_velocity_tolerance: 0

  position:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    constraints:
      goal_time: 10
      stopped_velocity_tolerance: 10



  grip_position:
    type: "position_controllers/JointPositionController"
    joint: gripper_actuator
