#!/usr/bin/env python

import rospy
from math import *
import numpy as np
import matplotlib.pyplot as plt 
import time

from geometry_msgs.msg import Pose
from daedalus_msgs.msg import OrientationState

plt.ion()

t = [0]
x_line = [0]
y_line = [0]
z_line = [0]
w_line = [0]
plt.plot(t, x_line, label='x')
plt.plot(t, y_line, label='y')
plt.plot(t, z_line, label='z')
plt.plot(t, w_line, label='w')
plt.legend()

w = [0.0, 0.0, 0.0, 0.0]

def quat_to_axis_angle(q):
    theta = 2*acos(q.w)
    x = q.x*theta/sin(theta/2)
    y = q.y*theta/sin(theta/2)
    z = q.z*theta/sin(theta/2)

    return (x, y, z, theta)

def cb(msg):
    w[0] = msg.orientation[0]
    w[1] = msg.orientation[1]
    w[2] = msg.orientation[2]
    w[3] = msg.orientation[3]
    
    #print("x", w[0], "y", w[1], "z", w[2], "w", w[3])

def pose_cb(msg):
    w[0] = msg.orientation.x
    w[1] = msg.orientation.y
    w[2] = msg.orientation.z
    w[3] = msg.orientation.w

def main():
    rospy.init_node('orientation_viewer')

    #rospy.Subscriber("/orientation_state", OrientationState, cb)
    rospy.Subscriber("/mujoco/object_pose", Pose, pose_cb)

    plt.show()

    iteration = 0

    while not rospy.is_shutdown():
        t.append(iteration)
        x_line.append(w[0])
        y_line.append(w[1])
        z_line.append(w[2])
        w_line.append(w[3])
        plt.scatter(t, x_line, c='blue')
        plt.scatter(t, y_line, c='orange')
        plt.scatter(t, z_line, c='green')
        plt.scatter(t, w_line, c='purple')
        plt.pause(0.001)
        iteration += 1

if __name__ == "__main__":
    main()