#!/usr/bin/env python

import rospy

from geometry_msgs.msg import Pose
import xml.etree.ElementTree as ET

rospy.init_node("remap_object_pose")
pub = rospy.Publisher("/ARM1/object_pose", Pose, queue_size=1)

def callback(msg):
    new_pose = msg
    # Subtract difference between base of arm and world origin
    new_pose.position.x -= 0.085
    new_pose.position.y -= 0.085
    pub.publish(new_pose)
    

def main():

    rospy.Subscriber("/mujoco/object_pose", Pose, callback)

    urdf_str = rospy.get_param("/robot_description")

    tree = ET.ElementTree(ET.fromstring(urdf_str))


    rospy.spin()

if __name__ == "__main__":
    main()