#!/usr/bin/env python

import os
import rospy

# This needs to be a rosparam
td3_logdir = os.getenv("TRAINING_DIR") + "TD3_logs"
vae_logdir = os.getenv("TRAINING_DIR") + "grasp_vae_logs"
CMD = "tensorboard --logdir " + td3_logdir 
print(CMD)
def main():
    rospy.loginfo("Access tensorboard at: http://nnu-engineering:6006/")
    os.system(CMD)

if __name__ == "__main__":
    main()

