#!/usr/bin/env python3.7

import rospy
import numpy as np
from mog_ai.grasp_vae import GraspVae
from mog_ai.srv import GenerateGrasp, GenerateGraspResponse
from geometry_msgs.msg import Pose

rospy.init_node("grasp_vae_server")
model_params = rospy.get_param("/model_config")
vae = GraspVae(latent_dim=model_params['latent_dim'], model_name=model_params['vae_path'])

def generate_cb(req):
    grasp = vae.generate_grasp(object_id=req.object_id, latent=list(req.latent_space))

    return GenerateGraspResponse(grasp)

def main():
    rospy.Service("/mog_ai/generate_grasp", GenerateGrasp, generate_cb)
    rospy.spin()

if __name__ == "__main__":
    main()

