#!/usr/bin/env python
import RPi.GPIO as GPIO
import time
import smach
# READ ME: this has nothing to do with apogee_robot_core it is ment to intigrate ember into the mission statemachiene
# Ethan Put this here because he is lazy and just needed a place to run it in python without ros

class Ember_High_State(smach.State):
    #Sends Ember a High using gpio launching ball 

    def __init__(self):
        smach.State.__init__(self, outcomes=['Done'])
        GPIO.setmode(GPIO.BCM)
        self.output_pin = 16 # Physical Pin no 36
        GPIO.setup(self.output_pin, GPIO.OUT, initial=GPIO.LOW)
 
 

    def execute(self, userdata):
        GPIO.output(self.output_pin, GPIO.HIGH)  
        time.sleep(2)
        GPIO.output(self.output_pin, GPIO.LOW)

        return 'Done'
    

class Simulation_SM:
    def __init__(self):

        # Create a SMACH state machine
        self.sm = smach.StateMachine(outcomes=["Mission_Success", "Mission_Fail"])

        self.mission_sm()
        
    def mission_sm(self):
        with self.sm:

            print("start state machine")

            smach.StateMachine.add('Ember_Test', Ember_High_State(),
                                    transitions={'Done': 'Mission_Success'})
            
    def run(self):
        #folding = rospy.get_param('joints/folding')
        #print(len(folding))
        outcome = self.sm.execute()


if __name__ == "__main__":
    sm = Simulation_SM()
    print("Begin Run SM")
    sm.run()
 