#!/usr/bin/env python

import rospy
import tf
from geometry_msgs.msg import Pose

class Broadcaster:
    def __init__(self):
        rospy.init_node("cam_tf_broadcaster")
        rospy.Subscriber("/cam_pose", Pose, self.cam_pose_cb)
        self.br = tf.TransformBroadcaster()
        self.rate = rospy.Rate(10.0)


        self.cam_pose = None

    def cam_pose_cb(self, msg):
        self.cam_pose = msg

    def run(self):
        while not rospy.is_shutdown():
            if self.cam_pose != None:
                self.br.sendTransform((self.cam_pose.position.x,
                                    self.cam_pose.position.y,
                                    self.cam_pose.position.z), 
                                    (0, 0, 0, 1),
                                    rospy.Time.now(),
                                    "depth_cam",
                                    "world")
            self.rate.sleep()


    

    



if __name__ == "__main__":
    b = Broadcaster()
    b.run()