#!/usr/bin/env python
import RPi.GPIO as GPIO
import time
import rospy


class Ember_High_State(smach.State):
    #Sends Ember a High using gpio launching ball 

    def __init__(self):
        smach.State.__init__(self, outcomes=['Done'])
        GPIO.setmode(GPIO.BCM)
        self.output_pin = 16 # Physical Pin no 36
        GPIO.setup(self.output_pin, GPIO.OUT, initial=GPIO.LOW)
 
 

    def execute(self, userdata):
        GPIO.output(self.output_pin, GPIO.HIGH)  
        time.sleep(2)
        GPIO.output(self.output_pin, GPIO.LOW)

        return 'Done'
