#!/usr/bin/env python
import RPi.GPIO as GPIO
import time
import rospy


GPIO.setmode(GPIO.BCM)
output_pin = 16 # Physical Pin no 36
GPIO.setup(output_pin, GPIO.OUT, initial=GPIO.LOW)

# 
def launch_ball():
    GPIO.output(output_pin, GPIO.HIGH)  
    time.sleep(2)
    GPIO.output(output_pin, GPIO.LOW)  

start_time = time.time()
launch_ball()

GPIO.cleanup()
